package bean;
// Generated 01/12/2023 10:35:20 by Hibernate Tools 4.3.1


import java.util.Date;
import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * ClientePhsb generated by hbm2java
 */
@Entity
@Table(name="cliente_phsb"
    ,catalog="db_pedro_barbosa"
)
public class ClientePhsb  implements java.io.Serializable {


     private int idclientePhsb;
     private String cpfPhsb;
     private String apelidoPhsb;
     private String nomePhsb;
     private Date dataNascimentoPhsb;
     private String telefonePhsb;
     private String sexoPhsb;
     private String rgPhsb;
     private String emailPhsb;
     private String cidadePhsb;
     private String estadoPhsb;
     private String cepPhsb;
     private Date dataCadastroPhsb;
     private String ultimaCompraPhsb;
     private Date dataEmissaorgPhsb;
     private String endereco;
  
    public  ClientePhsb(){
    }
	
    public ClientePhsb(int idclientePhsb) {
        this.idclientePhsb = idclientePhsb;
    }
    public ClientePhsb(int idclientePhsb, String cpfPhsb, String apelidoPhsb, String nomePhsb, Date dataNascimentoPhsb, String telefonePhsb, String sexoPhsb, String rgPhsb, String emailPhsb, String cidadePhsb, String estadoPhsb, String cepPhsb, Date dataCadastroPhsb, String ultimaCompraPhsb, Date dataEmissaorgPhsb, String endereco, Set vendaPhsbs) {
       this.idclientePhsb = idclientePhsb;
       this.cpfPhsb = cpfPhsb;
       this.apelidoPhsb = apelidoPhsb;
       this.nomePhsb = nomePhsb;
       this.dataNascimentoPhsb = dataNascimentoPhsb;
       this.telefonePhsb = telefonePhsb;
       this.sexoPhsb = sexoPhsb;
       this.rgPhsb = rgPhsb;
       this.emailPhsb = emailPhsb;
       this.cidadePhsb = cidadePhsb;
       this.estadoPhsb = estadoPhsb;
       this.cepPhsb = cepPhsb;
       this.dataCadastroPhsb = dataCadastroPhsb;
       this.ultimaCompraPhsb = ultimaCompraPhsb;
       this.dataEmissaorgPhsb = dataEmissaorgPhsb;
       this.endereco = endereco;
     
    }

   
     @Id 

    
    @Column(name="idcliente_phsb", unique=true, nullable=false)
    public int getIdclientePhsb() {
        return this.idclientePhsb;
    }
    
    public void setIdclientePhsb(int idclientePhsb) {
        this.idclientePhsb = idclientePhsb;
    }

    
    @Column(name="cpf_phsb", length=20)
    public String getCpfPhsb() {
        return this.cpfPhsb;
    }
    
    public void setCpfPhsb(String cpfPhsb) {
        this.cpfPhsb = cpfPhsb;
    }

    
    @Column(name="apelido_phsb", length=30)
    public String getApelidoPhsb() {
        return this.apelidoPhsb;
    }
    
    public void setApelidoPhsb(String apelidoPhsb) {
        this.apelidoPhsb = apelidoPhsb;
    }

    
    @Column(name="nome_phsb", length=40)
    public String getNomePhsb() {
        return this.nomePhsb;
    }
    
    public void setNomePhsb(String nomePhsb) {
        this.nomePhsb = nomePhsb;
    }

    @Temporal(TemporalType.DATE)
    @Column(name="data_nascimento_phsb", length=10)
    public Date getDataNascimentoPhsb() {
        return this.dataNascimentoPhsb;
    }
    
    public void setDataNascimentoPhsb(Date dataNascimentoPhsb) {
        this.dataNascimentoPhsb = dataNascimentoPhsb;
    }

    
    @Column(name="telefone_phsb", length=14)
    public String getTelefonePhsb() {
        return this.telefonePhsb;
    }
    
    public void setTelefonePhsb(String telefonePhsb) {
        this.telefonePhsb = telefonePhsb;
    }

    
    @Column(name="sexo_phsb", length=1)
    public String getSexoPhsb() {
        return this.sexoPhsb;
    }
    
    public void setSexoPhsb(String sexoPhsb) {
        this.sexoPhsb = sexoPhsb;
    }

    
    @Column(name="rg_phsb", length=15)
    public String getRgPhsb() {
        return this.rgPhsb;
    }
    
    public void setRgPhsb(String rgPhsb) {
        this.rgPhsb = rgPhsb;
    }

    
    @Column(name="email_phsb", length=45)
    public String getEmailPhsb() {
        return this.emailPhsb;
    }
    
    public void setEmailPhsb(String emailPhsb) {
        this.emailPhsb = emailPhsb;
    }

    
    @Column(name="cidade_phsb", length=30)
    public String getCidadePhsb() {
        return this.cidadePhsb;
    }
    
    public void setCidadePhsb(String cidadePhsb) {
        this.cidadePhsb = cidadePhsb;
    }

    
    @Column(name="estado_phsb", length=45)
    public String getEstadoPhsb() {
        return this.estadoPhsb;
    }
    
    public void setEstadoPhsb(String estadoPhsb) {
        this.estadoPhsb = estadoPhsb;
    }

    
    @Column(name="cep_phsb", length=11)
    public String getCepPhsb() {
        return this.cepPhsb;
    }
    
    public void setCepPhsb(String cepPhsb) {
        this.cepPhsb = cepPhsb;
    }

    @Temporal(TemporalType.DATE)
    @Column(name="data_cadastro_phsb", length=10)
    public Date getDataCadastroPhsb() {
        return this.dataCadastroPhsb;
    }
    
    public void setDataCadastroPhsb(Date dataCadastroPhsb) {
        this.dataCadastroPhsb = dataCadastroPhsb;
    }

    
    @Column(name="ultima_compra_phsb", length=30)
    public String getUltimaCompraPhsb() {
        return this.ultimaCompraPhsb;
    }
    
    public void setUltimaCompraPhsb(String ultimaCompraPhsb) {
        this.ultimaCompraPhsb = ultimaCompraPhsb;
    }

    @Temporal(TemporalType.DATE)
    @Column(name="data_emissaorg_phsb", length=10)
    public Date getDataEmissaorgPhsb() {
        return this.dataEmissaorgPhsb;
    }
    
    public void setDataEmissaorgPhsb(Date dataEmissaorgPhsb) {
        this.dataEmissaorgPhsb = dataEmissaorgPhsb;
    }

    
    @Column(name="endereco", length=20)
    public String getEndereco() {
        return this.endereco;
    }
    
    public void setEndereco(String endereco) {
        this.endereco = endereco;
    }



@Override
    public String toString() {
        return getNomePhsb();
    }

    public boolean equals(Object object) {

        if (object instanceof ClientePhsb) {
            ClientePhsb clientePhsb = (ClientePhsb) object;
            if (this.getIdclientePhsb()== clientePhsb.getIdclientePhsb()) {

                return true;
            }

        }
        return false;
    }
}





