package bean;
// Generated 19/10/2023 14:35:35 by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * ProdutoPhsb generated by hbm2java
 */
@Entity
@Table(name="produto_phsb"
    ,catalog="db_pedro_barbosa"
)
public class ProdutoPhsb  implements java.io.Serializable {


     private int idProdutoPhsb;
     private VendedorPhsb vendedorPhsb;
     private String tipoPhsb;
     private Integer valorPhsb;
     private String nomePhsb;


    public ProdutoPhsb() {
    }

	
    public ProdutoPhsb(int idProdutoPhsb, VendedorPhsb vendedorPhsb) {
        this.idProdutoPhsb = idProdutoPhsb;
        this.vendedorPhsb = vendedorPhsb;
    }
    public ProdutoPhsb(int idProdutoPhsb, VendedorPhsb vendedorPhsb, String tipoPhsb, Integer valorPhsb, String nomePhsb, Set vendaProdutoPhsbs) {
       this.idProdutoPhsb = idProdutoPhsb;
       this.vendedorPhsb = vendedorPhsb;
       this.tipoPhsb = tipoPhsb;
       this.valorPhsb = valorPhsb;
       this.nomePhsb = nomePhsb;
    
    }
   
     @Id 

    
    @Column(name="id_produto_phsb", unique=true, nullable=false)
    public int getIdProdutoPhsb() {
        return this.idProdutoPhsb;
    }
    
    public void setIdProdutoPhsb(int idProdutoPhsb) {
        this.idProdutoPhsb = idProdutoPhsb;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="fk_id_vendedor_phsb", nullable=false)
    public VendedorPhsb getVendedorPhsb() {
        return this.vendedorPhsb;
    }
    
    public void setVendedorPhsb(VendedorPhsb vendedorPhsb) {
        this.vendedorPhsb = vendedorPhsb;
    }

    
    @Column(name="tipo_phsb", length=20)
    public String getTipoPhsb() {
        return this.tipoPhsb;
    }
    
    public void setTipoPhsb(String tipoPhsb) {
        this.tipoPhsb = tipoPhsb;
    }

    
    @Column(name="valor_phsb")
    public Integer getValorPhsb() {
        return this.valorPhsb;
    }
    
    public void setValorPhsb(Integer valorPhsb) {
        this.valorPhsb = valorPhsb;
    }

    
    @Column(name="nome_phsb", length=20)
    public String getNomePhsb() {
        return this.nomePhsb;
    }
    
    public void setNomePhsb(String nomePhsb) {
        this.nomePhsb = nomePhsb;
    }




}


