package bean;
// Generated 01/12/2023 10:35:20 by Hibernate Tools 4.3.1



import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

/**
 * ProdutoPhsb generated by hbm2java
 */
@Entity
@Table(name="produto_phsb"
    ,catalog="db_pedro_barbosa"
)
public class ProdutoPhsb  implements java.io.Serializable {


     private int idprodutoPhsb;
     private VendedorPhsb vendedorPhsb;
     private String tipoPhsb;
     private double valorPhsb;
     private String nomePhsb;
     private String produtoPhsbcol;
    

    public ProdutoPhsb() {
    }

	
    public ProdutoPhsb(int idprodutoPhsb, VendedorPhsb vendedorPhsb, String tipoPhsb, double valorPhsb, String nomePhsb, String produtoPhsbcol) {
        this.idprodutoPhsb = idprodutoPhsb;
        this.vendedorPhsb = vendedorPhsb;
        this.tipoPhsb = tipoPhsb;
        this.valorPhsb = valorPhsb;
        this.nomePhsb = nomePhsb;
        this.produtoPhsbcol = produtoPhsbcol;
    }
    public ProdutoPhsb(int idprodutoPhsb, VendedorPhsb vendedorPhsb, String tipoPhsb, double valorPhsb, String nomePhsb, String produtoPhsbcol, Set vendaProdutoPhsbs) {
       this.idprodutoPhsb = idprodutoPhsb;
       this.vendedorPhsb = vendedorPhsb;
       this.tipoPhsb = tipoPhsb;
       this.valorPhsb = valorPhsb;
       this.nomePhsb = nomePhsb;
       this.produtoPhsbcol = produtoPhsbcol;
     
    }
   
     @Id 

    
    @Column(name="idproduto_phsb", unique=true, nullable=false)
    public int getIdprodutoPhsb() {
        return this.idprodutoPhsb;
    }
    
    public void setIdprodutoPhsb(int idprodutoPhsb) {
        this.idprodutoPhsb = idprodutoPhsb;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="fk_vendedor_phsb", nullable=false)
    public VendedorPhsb getVendedorPhsb() {
        return this.vendedorPhsb;
    }
    
    public void setVendedorPhsb(VendedorPhsb vendedorPhsb) {
        this.vendedorPhsb = vendedorPhsb;
    }

    
    @Column(name="tipo_phsb", nullable=false, length=45)
    public String getTipoPhsb() {
        return this.tipoPhsb;
    }
    
    public void setTipoPhsb(String tipoPhsb) {
        this.tipoPhsb = tipoPhsb;
    }

    
    @Column(name="valor_phsb", nullable=false, precision=10)
    public double getValorPhsb() {
        return this.valorPhsb;
    }
    
    public void setValorPhsb(double valorPhsb) {
        this.valorPhsb = valorPhsb;
    }

    
    @Column(name="nome_phsb", nullable=false, length=25)
    public String getNomePhsb() {
        return this.nomePhsb;
    }
    
    public void setNomePhsb(String nomePhsb) {
        this.nomePhsb = nomePhsb;
    }

    
    @Column(name="produto_phsbcol", nullable=false, length=45)
    public String getProdutoPhsbcol() {
        return this.produtoPhsbcol;
    }
    
    public void setProdutoPhsbcol(String produtoPhsbcol) {
        this.produtoPhsbcol = produtoPhsbcol;
    }





}


