package bean;
// Generated 19/10/2023 14:35:35 by Hibernate Tools 4.3.1


import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * UsuarioPhsb generated by hbm2java
 */
@Entity
@Table(name="usuario_phsb"
    ,catalog="db_pedro_barbosa"
)
public class UsuarioPhsb  implements java.io.Serializable {


     private int idUsuarioPhsb;
     private String nomePhsb;
     private String apelidoPhsb;
     private String cpfPhsb;
     private String senhaPhsb;
     private Date dataNascimentoPhsb;
     private String nivelPhsb;
     private String ativoPhsb;

    public UsuarioPhsb() {
    }

	
    public UsuarioPhsb(int idUsuarioPhsb) {
        this.idUsuarioPhsb = idUsuarioPhsb;
    }
    public UsuarioPhsb(int idUsuarioPhsb, String nomePhsb, String apelidoPhsb, String cpfPhsb, String senhaPhsb, Date dataNascimentoPhsb, String nivelPhsb, String ativoPhsb) {
       this.idUsuarioPhsb = idUsuarioPhsb;
       this.nomePhsb = nomePhsb;
       this.apelidoPhsb = apelidoPhsb;
       this.cpfPhsb = cpfPhsb;
       this.senhaPhsb = senhaPhsb;
       this.dataNascimentoPhsb = dataNascimentoPhsb;
       this.nivelPhsb = nivelPhsb;
       this.ativoPhsb = ativoPhsb;
    }
   
     @Id 

    
    @Column(name="id_usuario_phsb", unique=true, nullable=false)
    public int getIdUsuarioPhsb() {
        return this.idUsuarioPhsb;
    }
    
    public void setIdUsuarioPhsb(int idUsuarioPhsb) {
        this.idUsuarioPhsb = idUsuarioPhsb;
    }

    
    @Column(name="nome_phsb", length=20)
    public String getNomePhsb() {
        return this.nomePhsb;
    }
    
    public void setNomePhsb(String nomePhsb) {
        this.nomePhsb = nomePhsb;
    }

    
    @Column(name="apelido_phsb", length=20)
    public String getApelidoPhsb() {
        return this.apelidoPhsb;
    }
    
    public void setApelidoPhsb(String apelidoPhsb) {
        this.apelidoPhsb = apelidoPhsb;
    }

    
    @Column(name="cpf_phsb", length=14)
    public String getCpfPhsb() {
        return this.cpfPhsb;
    }
    
    public void setCpfPhsb(String cpfPhsb) {
        this.cpfPhsb = cpfPhsb;
    }

    
    @Column(name="senha_phsb", length=8)
    public String getSenhaPhsb() {
        return this.senhaPhsb;
    }
    
    public void setSenhaPhsb(String senhaPhsb) {
        this.senhaPhsb = senhaPhsb;
    }

    @Temporal(TemporalType.DATE)
    @Column(name="data_nascimento_phsb", length=10)
    public Date getDataNascimentoPhsb() {
        return this.dataNascimentoPhsb;
    }
    
    public void setDataNascimentoPhsb(Date dataNascimentoPhsb) {
        this.dataNascimentoPhsb = dataNascimentoPhsb;
    }

    
    @Column(name="nivel_phsb", length=1)
    public String getNivelPhsb() {
        return this.nivelPhsb;
    }
    
    public void setNivelPhsb(String nivelPhsb) {
        this.nivelPhsb = nivelPhsb;
    }

    
    @Column(name="ativo_phsb", length=1)
    public String getAtivoPhsb() {
        return this.ativoPhsb;
    }
    
    public void setAtivoPhsb(String ativoPhsb) {
        this.ativoPhsb = ativoPhsb;
    }




}


