package bean;
// Generated 19/10/2023 14:35:35 by Hibernate Tools 4.3.1


import java.util.Date;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * VendaPhsb generated by hbm2java
 */
@Entity
@Table(name="Venda_PHSB"
    ,catalog="db_pedro_barbosa"
)
public class VendaPhsb  implements java.io.Serializable {


     private int idVendaPhsb;
     private ClientePhsb clientePhsb;
     private VendedorPhsb vendedorPhsb;
     private Date dataPhsb;
     private int valorTotalPhsb;


    public VendaPhsb() {
    }

	
    public VendaPhsb(int idVendaPhsb, ClientePhsb clientePhsb, VendedorPhsb vendedorPhsb) {
        this.idVendaPhsb = idVendaPhsb;
        this.clientePhsb = clientePhsb;
        this.vendedorPhsb = vendedorPhsb;
    }
    public VendaPhsb(int idVendaPhsb, ClientePhsb clientePhsb, VendedorPhsb vendedorPhsb, Date dataPhsb, int valorTotalPhsb, Set vendaProdutoPhsbs) {
       this.idVendaPhsb = idVendaPhsb;
       this.clientePhsb = clientePhsb;
       this.vendedorPhsb = vendedorPhsb;
       this.dataPhsb = dataPhsb;
       this.valorTotalPhsb = valorTotalPhsb;
    
    }
   
     @Id 

    
    @Column(name="id_venda_PHSB", unique=true, nullable=false)
    public int getIdVendaPhsb() {
        return this.idVendaPhsb;
    }
    
    public void setIdVendaPhsb(int idVendaPhsb) {
        this.idVendaPhsb = idVendaPhsb;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="fk_id_cliente_phsb", nullable=false)
    public ClientePhsb getClientePhsb() {
        return this.clientePhsb;
    }
    
    public void setClientePhsb(ClientePhsb clientePhsb) {
        this.clientePhsb = clientePhsb;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="fk_id_vendedor_phsb", nullable=false)
    public VendedorPhsb getVendedorPhsb() {
        return this.vendedorPhsb;
    }
    
    public void setVendedorPhsb(VendedorPhsb vendedorPhsb) {
        this.vendedorPhsb = vendedorPhsb;
    }

    @Temporal(TemporalType.DATE)
    @Column(name="data_PHSB", length=10)
    public Date getDataPhsb() {
        return this.dataPhsb;
    }
    
    public void setDataPhsb(Date dataPhsb) {
        this.dataPhsb = dataPhsb;
    }

    
    @Column(name="valor_total_PHSB")
    public int getValorTotalPhsb() {
        return this.valorTotalPhsb;
    }
    
    public void setValorTotalPhsb(int valorTotalPhsb) {
        this.valorTotalPhsb = valorTotalPhsb;
    }




}


