package bean;
// Generated 19/10/2023 14:35:35 by Hibernate Tools 4.3.1


import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

/**
 * VendaProdutoPhsb generated by hbm2java
 */
@Entity
@Table(name="venda_produto_phsb"
    ,catalog="db_pedro_barbosa"
)
public class VendaProdutoPhsb  implements java.io.Serializable {


     private int idVendaProdutoPhsb;
     private VendaPhsb vendaPhsb;
     private ProdutoPhsb produtoPhsb;
     private Integer valorUnitario;

    public VendaProdutoPhsb() {
    }

	
    public VendaProdutoPhsb(int idVendaProdutoPhsb, VendaPhsb vendaPhsb, ProdutoPhsb produtoPhsb) {
        this.idVendaProdutoPhsb = idVendaProdutoPhsb;
        this.vendaPhsb = vendaPhsb;
        this.produtoPhsb = produtoPhsb;
    }
    public VendaProdutoPhsb(int idVendaProdutoPhsb, VendaPhsb vendaPhsb, ProdutoPhsb produtoPhsb, Integer valorUnitario) {
       this.idVendaProdutoPhsb = idVendaProdutoPhsb;
       this.vendaPhsb = vendaPhsb;
       this.produtoPhsb = produtoPhsb;
       this.valorUnitario = valorUnitario;
    }
   
     @Id 

    
    @Column(name="id_venda_produto_phsb", unique=true, nullable=false)
    public int getIdVendaProdutoPhsb() {
        return this.idVendaProdutoPhsb;
    }
    
    public void setIdVendaProdutoPhsb(int idVendaProdutoPhsb) {
        this.idVendaProdutoPhsb = idVendaProdutoPhsb;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="fk_id_venda_phsb", nullable=false)
    public VendaPhsb getVendaPhsb() {
        return this.vendaPhsb;
    }
    
    public void setVendaPhsb(VendaPhsb vendaPhsb) {
        this.vendaPhsb = vendaPhsb;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="fk_id_produto_phsb", nullable=false)
    public ProdutoPhsb getProdutoPhsb() {
        return this.produtoPhsb;
    }
    
    public void setProdutoPhsb(ProdutoPhsb produtoPhsb) {
        this.produtoPhsb = produtoPhsb;
    }

    
    @Column(name="valor_unitario")
    public Integer getValorUnitario() {
        return this.valorUnitario;
    }
    
    public void setValorUnitario(Integer valorUnitario) {
        this.valorUnitario = valorUnitario;
    }




}


