package bean;
// Generated 01/12/2023 10:35:20 by Hibernate Tools 4.3.1



import java.util.Date;
import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * VendaPhsb generated by hbm2java
 */
@Entity
@Table(name="venda_phsb"
    ,catalog="db_pedro_barbosa"
)
public class VendaPhsb  implements java.io.Serializable {


     private int idvendaPhsb;
     private ClientePhsb clientePhsb;
     private int fkVendedorPhsb;
     private Date dataPhsb;
     private double valortotalPhsb;
   

    public VendaPhsb() {
    }

	
    public VendaPhsb(int idvendaPhsb, ClientePhsb clientePhsb, int fkVendedorPhsb, Date dataPhsb, double valortotalPhsb) {
        this.idvendaPhsb = idvendaPhsb;
        this.clientePhsb = clientePhsb;
        this.fkVendedorPhsb = fkVendedorPhsb;
        this.dataPhsb = dataPhsb;
        this.valortotalPhsb = valortotalPhsb;
    }
    public VendaPhsb(int idvendaPhsb, ClientePhsb clientePhsb, int fkVendedorPhsb, Date dataPhsb, double valortotalPhsb, Set vendaProdutoPhsbs) {
       this.idvendaPhsb = idvendaPhsb;
       this.clientePhsb = clientePhsb;
       this.fkVendedorPhsb = fkVendedorPhsb;
       this.dataPhsb = dataPhsb;
       this.valortotalPhsb = valortotalPhsb;
       
    }
   
     @Id 

    
    @Column(name="idvenda_phsb", unique=true, nullable=false)
    public int getIdvendaPhsb() {
        return this.idvendaPhsb;
    }
    
    public void setIdvendaPhsb(int idvendaPhsb) {
        this.idvendaPhsb = idvendaPhsb;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="fk_cliente_phsb", nullable=false)
    public ClientePhsb getClientePhsb() {
        return this.clientePhsb;
    }
    
    public void setClientePhsb(ClientePhsb clientePhsb) {
        this.clientePhsb = clientePhsb;
    }

    
    @Column(name="fk_vendedor_phsb", nullable=false)
    public int getFkVendedorPhsb() {
        return this.fkVendedorPhsb;
    }
    
    public void setFkVendedorPhsb(int fkVendedorPhsb) {
        this.fkVendedorPhsb = fkVendedorPhsb;
    }

    @Temporal(TemporalType.DATE)
    @Column(name="data_phsb", nullable=false, length=10)
    public Date getDataPhsb() {
        return this.dataPhsb;
    }
    
    public void setDataPhsb(Date dataPhsb) {
        this.dataPhsb = dataPhsb;
    }

    
    @Column(name="valortotal_phsb", nullable=false, precision=10)
    public double getValortotalPhsb() {
        return this.valortotalPhsb;
    }
    
    public void setValortotalPhsb(double valortotalPhsb) {
        this.valortotalPhsb = valortotalPhsb;
    }

    public void setFkVendedorPhsb() {
        throw new UnsupportedOperationException("Not supported yet."); //To change body of generated methods, choose Tools | Templates.
    }





}


