package bean;
// Generated 08/12/2023 12:09:27 by Hibernate Tools 4.3.1

import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * VendedorPhsb generated by hbm2java
 */
@Entity
@Table(name = "vendedor_phsb",
         catalog = "db_pedro_barbosa"
)
public class VendedorPhsb implements java.io.Serializable {

    private int idvendedorPhsb;
    private String nomePhsb;
    private String cidadePhsb;
    private String cpfPhsb;
    private String rgPhsb;

    public VendedorPhsb() {
    }

    public VendedorPhsb(int idvendedorPhsb, String nomePhsb, String cidadePhsb, String cpfPhsb, String rgPhsb) {
        this.idvendedorPhsb = idvendedorPhsb;
        this.nomePhsb = nomePhsb;
        this.cidadePhsb = cidadePhsb;
        this.cpfPhsb = cpfPhsb;
        this.rgPhsb = rgPhsb;
    }

    public VendedorPhsb(int idvendedorPhsb, String nomePhsb, String cidadePhsb, String cpfPhsb, String rgPhsb, Set produtoPhsbs, Set vendaPhsbs) {
        this.idvendedorPhsb = idvendedorPhsb;
        this.nomePhsb = nomePhsb;
        this.cidadePhsb = cidadePhsb;
        this.cpfPhsb = cpfPhsb;
        this.rgPhsb = rgPhsb;

    }

    @Id

    @Column(name = "idvendedor_phsb", unique = true, nullable = false)
    public int getIdvendedorPhsb() {
        return this.idvendedorPhsb;
    }

    public void setIdvendedorPhsb(int idvendedorPhsb) {
        this.idvendedorPhsb = idvendedorPhsb;
    }

    @Column(name = "nome_phsb", nullable = false, length = 30)
    public String getNomePhsb() {
        return this.nomePhsb;
    }

    public void setNomePhsb(String nomePhsb) {
        this.nomePhsb = nomePhsb;
    }

    @Column(name = "cidade_phsb", nullable = false, length = 30)
    public String getCidadePhsb() {
        return this.cidadePhsb;
    }

    public void setCidadePhsb(String cidadePhsb) {
        this.cidadePhsb = cidadePhsb;
    }

    @Column(name = "cpf_phsb", nullable = false, length = 14)
    public String getCpfPhsb() {
        return this.cpfPhsb;
    }

    public void setCpfPhsb(String cpfPhsb) {
        this.cpfPhsb = cpfPhsb;
    }

    @Column(name = "rg_phsb", nullable = false, length = 45)
    public String getRgPhsb() {
        return this.rgPhsb;
    }

    public void setRgPhsb(String rgPhsb) {
        this.rgPhsb = rgPhsb;
    }

    public String toString() {

        return getNomePhsb();
    }
    
  
    public boolean equals(Object object) {
        if (object instanceof ClientePhsb) {
            VendedorPhsb vendedorPhsb = (VendedorPhsb) object;
            if (this.getIdvendedorPhsb()== vendedorPhsb.getIdvendedorPhsb()) {
                return true;
            }            
        }
        return true;
    }


}
