package Bean;
// Generated 14/09/2023 08:42:43 by Hibernate Tools 4.3.1


import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

/**
 * VendaProdutoPhsb generated by hbm2java
 */
@Entity
@Table(name="venda_produto_phsb"
    ,catalog="db_pedro_barbosa"
)
public class VendaProdutoPhsb  implements java.io.Serializable {


     private int idVendaProdutoPhsb;
     private int vendaPhsb;
     private int produtoPhsb;

    public VendaProdutoPhsb() {
    }

    public VendaProdutoPhsb(int idVendaProdutoPhsb, int vendaPhsb, int produtoPhsb) {
       this.idVendaProdutoPhsb = idVendaProdutoPhsb;
       this.vendaPhsb = vendaPhsb;
       this.produtoPhsb = produtoPhsb;
    }
   
     @Id 

    
    @Column(name="id_venda_produto_phsb", unique=true, nullable=false)
    public int getIdVendaProdutoPhsb() {
        return this.idVendaProdutoPhsb;
    }
    
    public void setIdVendaProdutoPhsb(int idVendaProdutoPhsb) {
        this.idVendaProdutoPhsb = idVendaProdutoPhsb;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="fk_id_venda_phsb", nullable=false)
    public int getVendaPhsb() {
        return this.vendaPhsb;
    }
    
    public void setVendaPhsb(int vendaPhsb) {
        this.vendaPhsb = vendaPhsb;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="fk_id_produto_phsb", nullable=false)
    public int getProdutoPhsb() {
        return this.produtoPhsb;
    }
    
    public void setProdutoPhsb(int produtoPhsb) {
        this.produtoPhsb = produtoPhsb;
    }




}


