/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package View;

/**
 *
 * @author u09219761190
 */
public class JFrmToolBar extends javax.swing.JFrame {

    JFrmLogin jFrmLogin2;
 
    
    /**
     * Creates new form JFrmToolBar
     */
    public JFrmToolBar() {
        initComponents();
        setLocationRelativeTo(null);
        setTitle("ToolBar");
        
        
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jMenuItem5 = new javax.swing.JMenuItem();
        jPanel1 = new javax.swing.JPanel();
        jBtnSair = new javax.swing.JButton();
        jToolBar1 = new javax.swing.JToolBar();
        jBtnUsuariosTool = new javax.swing.JButton();
        jBtnClienteTool = new javax.swing.JButton();
        jBtnProdutoTool = new javax.swing.JButton();
        jBtnVendedorTool = new javax.swing.JButton();

        jMenuItem5.setText("jMenuItem5");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));

        jBtnSair.setIcon(new javax.swing.ImageIcon(getClass().getResource("/IMG/door_in.png"))); // NOI18N
        jBtnSair.setText("Sair");
        jBtnSair.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtnSairActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(313, Short.MAX_VALUE)
                .addComponent(jBtnSair)
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jBtnSair)
                .addContainerGap())
        );

        jToolBar1.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jToolBar1.setRollover(true);

        jBtnUsuariosTool.setIcon(new javax.swing.ImageIcon(getClass().getResource("/IMG/group.png"))); // NOI18N
        jBtnUsuariosTool.setText("Usuarios");
        jBtnUsuariosTool.setFocusable(false);
        jBtnUsuariosTool.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jBtnUsuariosTool.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        jBtnUsuariosTool.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtnUsuariosToolActionPerformed(evt);
            }
        });
        jToolBar1.add(jBtnUsuariosTool);

        jBtnClienteTool.setIcon(new javax.swing.ImageIcon(getClass().getResource("/IMG/cliente.png"))); // NOI18N
        jBtnClienteTool.setText("Cliente");
        jBtnClienteTool.setFocusable(false);
        jBtnClienteTool.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jBtnClienteTool.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        jBtnClienteTool.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtnClienteToolActionPerformed(evt);
            }
        });
        jToolBar1.add(jBtnClienteTool);

        jBtnProdutoTool.setIcon(new javax.swing.ImageIcon(getClass().getResource("/IMG/cart_put.png"))); // NOI18N
        jBtnProdutoTool.setText("Produto");
        jBtnProdutoTool.setFocusable(false);
        jBtnProdutoTool.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jBtnProdutoTool.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        jBtnProdutoTool.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtnProdutoToolActionPerformed(evt);
            }
        });
        jToolBar1.add(jBtnProdutoTool);

        jBtnVendedorTool.setIcon(new javax.swing.ImageIcon(getClass().getResource("/IMG/icons8-fornecedor-30.png"))); // NOI18N
        jBtnVendedorTool.setText("Vendedor");
        jBtnVendedorTool.setFocusable(false);
        jBtnVendedorTool.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jBtnVendedorTool.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        jBtnVendedorTool.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtnVendedorToolActionPerformed(evt);
            }
        });
        jToolBar1.add(jBtnVendedorTool);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jToolBar1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addComponent(jToolBar1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 188, Short.MAX_VALUE)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jBtnSairActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtnSairActionPerformed
        // TODO add your handling code here:
        System.exit(0);
    }//GEN-LAST:event_jBtnSairActionPerformed

    private void jBtnUsuariosToolActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtnUsuariosToolActionPerformed
        // TODO add your handling code here:
         JDlgUsuario jDlgUsuario = new JDlgUsuario(null, true);
        jDlgUsuario.setVisible(true);
    }//GEN-LAST:event_jBtnUsuariosToolActionPerformed

    private void jBtnClienteToolActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtnClienteToolActionPerformed
        // TODO add your handling code here:
           JDlgCliente jDlgCliente = new JDlgCliente(null, true);
        jDlgCliente.setVisible(true);
    }//GEN-LAST:event_jBtnClienteToolActionPerformed

    private void jBtnProdutoToolActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtnProdutoToolActionPerformed
        // TODO add your handling code here:
             JDlgProdutoNovo jDlgProduto = new JDlgProdutoNovo(null, true);
        jDlgProduto.setVisible(true);
    }//GEN-LAST:event_jBtnProdutoToolActionPerformed

    private void jBtnVendedorToolActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtnVendedorToolActionPerformed
        // TODO add your handling code here:
           JDlgVendedorNovo jDlgVendedorNovo = new JDlgVendedorNovo(null, true);
        jDlgVendedorNovo.setVisible(true);
    }//GEN-LAST:event_jBtnVendedorToolActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(JFrmToolBar.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(JFrmToolBar.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(JFrmToolBar.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(JFrmToolBar.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                JFrmLogin jFrmLogin = new JFrmLogin();
                jFrmLogin.setVisible(true);
               
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jBtnClienteTool;
    private javax.swing.JButton jBtnProdutoTool;
    private javax.swing.JButton jBtnSair;
    private javax.swing.JButton jBtnUsuariosTool;
    private javax.swing.JButton jBtnVendedorTool;
    private javax.swing.JMenuItem jMenuItem5;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JToolBar jToolBar1;
    // End of variables declaration//GEN-END:variables
}
