/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package View;

import consultas.JDlgUsuarioConsulta;
import View.JFrmLogin;
import consultas.JDlgClienteConsulta;
import consultas.JDlgProdutoConsulta;
import consultas.JDlgVendaConsulta;
import consultas.JDlgVendedorConsulta;
import View.JDlgVenda_produto;

/**
 *
 * @author u09219761190
 */
public class JFrmPrincipal extends javax.swing.JFrame {

    /**
     * Creates new form JFrmPrincipal
     */
    public JFrmPrincipal() {
        initComponents();
        setTitle("Tela de Menu");
        setLocationRelativeTo(null);
//            JFrmLogin jFrmLogin2 = new JFrmLogin();

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jMenuItem1 = new javax.swing.JMenuItem();
        jMenuBar2 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        jMenu4 = new javax.swing.JMenu();
        jMenu5 = new javax.swing.JMenu();
        jPanel1 = new javax.swing.JPanel();
        jBtnSair = new javax.swing.JButton();
        jToolBar1 = new javax.swing.JToolBar();
        jBtnUsuariosTool = new javax.swing.JButton();
        jBtnClienteTool = new javax.swing.JButton();
        jBtnProdutoTool = new javax.swing.JButton();
        jBtnVendedorTool = new javax.swing.JButton();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu2 = new javax.swing.JMenu();
        jMnuUsuario2 = new javax.swing.JMenuItem();
        jMnuCliente2 = new javax.swing.JMenuItem();
        jMnuProduto = new javax.swing.JMenuItem();
        jMenu3 = new javax.swing.JMenu();
        jMnuVenda = new javax.swing.JMenuItem();
        jMnuVenda_produtor = new javax.swing.JMenuItem();
        jMenu6 = new javax.swing.JMenu();
        jMenucClienteConsul = new javax.swing.JMenuItem();
        jMenuProdutoConsul = new javax.swing.JMenuItem();
        jMenuVendaConsul = new javax.swing.JMenuItem();
        jMenuUsuarioConsul = new javax.swing.JMenuItem();
        jMenuVendedorConsul = new javax.swing.JMenuItem();

        jMenuItem1.setText("jMenuItem1");

        jMenu1.setText("File");
        jMenuBar2.add(jMenu1);

        jMenu4.setText("Edit");
        jMenuBar2.add(jMenu4);

        jMenu5.setText("jMenu5");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));

        jBtnSair.setIcon(new javax.swing.ImageIcon(getClass().getResource("/IMG/door_in.png"))); // NOI18N
        jBtnSair.setText("Sair");
        jBtnSair.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtnSairActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(313, Short.MAX_VALUE)
                .addComponent(jBtnSair)
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jBtnSair)
                .addContainerGap())
        );

        jToolBar1.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jToolBar1.setRollover(true);

        jBtnUsuariosTool.setIcon(new javax.swing.ImageIcon(getClass().getResource("/IMG/group.png"))); // NOI18N
        jBtnUsuariosTool.setText("Usuarios");
        jBtnUsuariosTool.setFocusable(false);
        jBtnUsuariosTool.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jBtnUsuariosTool.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        jBtnUsuariosTool.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtnUsuariosToolActionPerformed(evt);
            }
        });
        jToolBar1.add(jBtnUsuariosTool);

        jBtnClienteTool.setIcon(new javax.swing.ImageIcon(getClass().getResource("/IMG/cliente.png"))); // NOI18N
        jBtnClienteTool.setText("Cliente");
        jBtnClienteTool.setFocusable(false);
        jBtnClienteTool.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jBtnClienteTool.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        jBtnClienteTool.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtnClienteToolActionPerformed(evt);
            }
        });
        jToolBar1.add(jBtnClienteTool);

        jBtnProdutoTool.setIcon(new javax.swing.ImageIcon(getClass().getResource("/IMG/cart_put.png"))); // NOI18N
        jBtnProdutoTool.setText("Produto");
        jBtnProdutoTool.setFocusable(false);
        jBtnProdutoTool.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jBtnProdutoTool.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        jBtnProdutoTool.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtnProdutoToolActionPerformed(evt);
            }
        });
        jToolBar1.add(jBtnProdutoTool);

        jBtnVendedorTool.setIcon(new javax.swing.ImageIcon(getClass().getResource("/IMG/icons8-fornecedor-30.png"))); // NOI18N
        jBtnVendedorTool.setText("Vendedor");
        jBtnVendedorTool.setFocusable(false);
        jBtnVendedorTool.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jBtnVendedorTool.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        jBtnVendedorTool.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtnVendedorToolActionPerformed(evt);
            }
        });
        jToolBar1.add(jBtnVendedorTool);

        jMenu2.setText("Cadastro");

        jMnuUsuario2.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_U, java.awt.event.InputEvent.CTRL_MASK));
        jMnuUsuario2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/IMG/user_go.png"))); // NOI18N
        jMnuUsuario2.setText("Usuario");
        jMnuUsuario2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMnuUsuario2ActionPerformed(evt);
            }
        });
        jMenu2.add(jMnuUsuario2);

        jMnuCliente2.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_F, java.awt.event.InputEvent.CTRL_MASK));
        jMnuCliente2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/IMG/cliente.png"))); // NOI18N
        jMnuCliente2.setText("Cliente");
        jMnuCliente2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMnuCliente2ActionPerformed(evt);
            }
        });
        jMenu2.add(jMnuCliente2);

        jMnuProduto.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_P, java.awt.event.InputEvent.CTRL_MASK));
        jMnuProduto.setIcon(new javax.swing.ImageIcon(getClass().getResource("/IMG/icons8-mega-sales-30.png"))); // NOI18N
        jMnuProduto.setText("Produto");
        jMnuProduto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMnuProdutoActionPerformed(evt);
            }
        });
        jMenu2.add(jMnuProduto);

        jMenuBar1.add(jMenu2);

        jMenu3.setText("Movimento");

        jMnuVenda.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_C, java.awt.event.InputEvent.CTRL_MASK));
        jMnuVenda.setText("Venda");
        jMnuVenda.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMnuVendaActionPerformed(evt);
            }
        });
        jMenu3.add(jMnuVenda);

        jMnuVenda_produtor.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_C, java.awt.event.InputEvent.SHIFT_MASK));
        jMnuVenda_produtor.setText("Venda_produto");
        jMnuVenda_produtor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMnuVenda_produtorActionPerformed(evt);
            }
        });
        jMenu3.add(jMnuVenda_produtor);

        jMenuBar1.add(jMenu3);

        jMenu6.setText("Consultas");

        jMenucClienteConsul.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_C, java.awt.event.InputEvent.CTRL_MASK));
        jMenucClienteConsul.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/user.png"))); // NOI18N
        jMenucClienteConsul.setText("Cliente");
        jMenucClienteConsul.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenucClienteConsulActionPerformed(evt);
            }
        });
        jMenu6.add(jMenucClienteConsul);

        jMenuProdutoConsul.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_P, java.awt.event.InputEvent.CTRL_MASK));
        jMenuProdutoConsul.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/cart_add.png"))); // NOI18N
        jMenuProdutoConsul.setText("Produto");
        jMenuProdutoConsul.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuProdutoConsulActionPerformed(evt);
            }
        });
        jMenu6.add(jMenuProdutoConsul);

        jMenuVendaConsul.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_V, java.awt.event.InputEvent.ALT_MASK));
        jMenuVendaConsul.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/pencil.png"))); // NOI18N
        jMenuVendaConsul.setText("Venda");
        jMenuVendaConsul.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuVendaConsulActionPerformed(evt);
            }
        });
        jMenu6.add(jMenuVendaConsul);

        jMenuUsuarioConsul.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_C, java.awt.event.InputEvent.CTRL_MASK));
        jMenuUsuarioConsul.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/user_red.png"))); // NOI18N
        jMenuUsuarioConsul.setText("Usuario");
        jMenuUsuarioConsul.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuUsuarioConsulActionPerformed(evt);
            }
        });
        jMenu6.add(jMenuUsuarioConsul);

        jMenuVendedorConsul.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_V, java.awt.event.InputEvent.CTRL_MASK));
        jMenuVendedorConsul.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/icons8-fornecedor-30.png"))); // NOI18N
        jMenuVendedorConsul.setText("Vendedor");
        jMenuVendedorConsul.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuVendedorConsulActionPerformed(evt);
            }
        });
        jMenu6.add(jMenuVendedorConsul);

        jMenuBar1.add(jMenu6);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jToolBar1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addComponent(jToolBar1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 167, Short.MAX_VALUE)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jMnuUsuario2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMnuUsuario2ActionPerformed
        JDlgUsuario jDlgUsuario2 = new JDlgUsuario(null, true);
        jDlgUsuario2.setVisible(true);
    }//GEN-LAST:event_jMnuUsuario2ActionPerformed

    private void jMnuCliente2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMnuCliente2ActionPerformed
        JDlgCliente jDlgCliente = new JDlgCliente(null, true);
        jDlgCliente.setVisible(true);
    }//GEN-LAST:event_jMnuCliente2ActionPerformed

    private void jMnuProdutoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMnuProdutoActionPerformed
        JDlgProdutoNovo jDlgProduto = new JDlgProdutoNovo(null, true);
        jDlgProduto.setVisible(true);
    }//GEN-LAST:event_jMnuProdutoActionPerformed

    private void jMnuVendaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMnuVendaActionPerformed
        JDlgVenda jDlgVenda = new JDlgVenda(null, true);
        jDlgVenda.setVisible(true);
    }//GEN-LAST:event_jMnuVendaActionPerformed

    private void jMnuVenda_produtorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMnuVenda_produtorActionPerformed
        JDlgVenda_produto jDlgVenda_produto = new JDlgVenda_produto(null, true);
        jDlgVenda_produto.setVisible(true);
    }//GEN-LAST:event_jMnuVenda_produtorActionPerformed

    private void jBtnSairActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtnSairActionPerformed
        // TODO add your handling code here:
        System.exit(0);
    }//GEN-LAST:event_jBtnSairActionPerformed

    private void jBtnUsuariosToolActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtnUsuariosToolActionPerformed
        // TODO add your handling code here:
        JDlgUsuario jDlgUsuario = new JDlgUsuario(null, true);
        jDlgUsuario.setVisible(true);
    }//GEN-LAST:event_jBtnUsuariosToolActionPerformed

    private void jBtnClienteToolActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtnClienteToolActionPerformed
        // TODO add your handling code here:
        JDlgCliente jDlgCliente = new JDlgCliente(null, true);
        jDlgCliente.setVisible(true);
    }//GEN-LAST:event_jBtnClienteToolActionPerformed

    private void jBtnProdutoToolActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtnProdutoToolActionPerformed
        // TODO add your handling code here:
        JDlgProdutoNovo jDlgProduto = new JDlgProdutoNovo(null, true);
        jDlgProduto.setVisible(true);
    }//GEN-LAST:event_jBtnProdutoToolActionPerformed

    private void jBtnVendedorToolActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtnVendedorToolActionPerformed
        // TODO add your handling code here:
        JDlgVendedorNovo jDlgVendedorNovo = new JDlgVendedorNovo(null, true);
        jDlgVendedorNovo.setVisible(true);
    }//GEN-LAST:event_jBtnVendedorToolActionPerformed

    private void jMenuVendedorConsulActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuVendedorConsulActionPerformed
        // TODO add your handling code here:
        JDlgVendedorConsulta jDlgVendedorConsulta = new JDlgVendedorConsulta(null, true);
        jDlgVendedorConsulta.setVisible(true);
    }//GEN-LAST:event_jMenuVendedorConsulActionPerformed

    private void jMenuProdutoConsulActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuProdutoConsulActionPerformed
        // TODO add your handling code here:
        JDlgProdutoConsulta jDlgProdutoConsulta = new JDlgProdutoConsulta(null, true);
        jDlgProdutoConsulta.setVisible(true);
    }//GEN-LAST:event_jMenuProdutoConsulActionPerformed

    private void jMenucClienteConsulActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenucClienteConsulActionPerformed
        // TODO add your handling code here:
        JDlgClienteConsulta jDlgClienteConsulta = new JDlgClienteConsulta(null, true);
        jDlgClienteConsulta.setVisible(true);

    }//GEN-LAST:event_jMenucClienteConsulActionPerformed

    private void jMenuUsuarioConsulActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuUsuarioConsulActionPerformed
        // TODO add your handling code here:
        JDlgUsuarioConsulta jDlgUsuarioConsulta = new JDlgUsuarioConsulta(null, true);
        jDlgUsuarioConsulta.setVisible(true);

    }//GEN-LAST:event_jMenuUsuarioConsulActionPerformed

    private void jMenuVendaConsulActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuVendaConsulActionPerformed
        // TODO add your handling code here:

        JDlgVendaConsulta jDlgVendaConsulta = new JDlgVendaConsulta(null, true);
        jDlgVendaConsulta.setVisible(true);

    }//GEN-LAST:event_jMenuVendaConsulActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(JFrmPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(JFrmPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(JFrmPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(JFrmPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new JFrmLogin().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jBtnClienteTool;
    private javax.swing.JButton jBtnProdutoTool;
    private javax.swing.JButton jBtnSair;
    private javax.swing.JButton jBtnUsuariosTool;
    private javax.swing.JButton jBtnVendedorTool;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenu jMenu3;
    private javax.swing.JMenu jMenu4;
    private javax.swing.JMenu jMenu5;
    private javax.swing.JMenu jMenu6;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuBar jMenuBar2;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JMenuItem jMenuProdutoConsul;
    private javax.swing.JMenuItem jMenuUsuarioConsul;
    private javax.swing.JMenuItem jMenuVendaConsul;
    private javax.swing.JMenuItem jMenuVendedorConsul;
    private javax.swing.JMenuItem jMenucClienteConsul;
    private javax.swing.JMenuItem jMnuCliente2;
    private javax.swing.JMenuItem jMnuProduto;
    private javax.swing.JMenuItem jMnuUsuario2;
    private javax.swing.JMenuItem jMnuVenda;
    private javax.swing.JMenuItem jMnuVenda_produtor;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JToolBar jToolBar1;
    // End of variables declaration//GEN-END:variables
}
